apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-server.fullname" . }}-secrets
  labels:
    {{- include "todo-server.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.env.OPENAI_API_KEY | b64enc | quote }}
  better-auth-secret: {{ .Values.env.BETTER_AUTH_SECRET | b64enc | quote }}